# a plain text file where you write HTTP requests in a readable format.

### Get products
GET http://127.0.0.1:8000/products/

### Create product
POST http://127.0.0.1:8000/products/
Content-Type: application/json

{
    "name": "Axis - Y Dark Spot Correcting Glow Serum",
    "description": "Vegan, cruelty-free, and suitable for all skin types, including sensitive skin.",
    "price": "1785.00",
    "stock": 50,
    "category": 1
}

### Get categories list
GET http://127.0.0.1:8000/products/categories/

### Create a Category
POST http://127.0.0.1:8000/products/categories/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5OTY0MTQyLCJpYXQiOjE3Njk5NjM4NDIsImp0aSI6ImNhMmMwNmEyZDQxMDRmNTY4Yzc3ZTZkOWNhMmNmYmFhIiwidXNlcl9pZCI6IjEifQ.L9lUWqMqGt-xYm2CuasaDef4K1A8URWbgWEhmw7igRw

{
    "name": "Fashion",
    "slug": "fashion",
    "description": "Clothing, footwear, and fashion accessories for all ages.",
    "is_active": true
}