# a plain text file where you write HTTP requests in a readable format.

### Get products
GET http://127.0.0.1:8000/products/

### Create product
POST http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMDE4NDYyLCJpYXQiOjE3NzAwMTgxNjIsImp0aSI6IjU3N2MzMDljMmY4NzQ3ODNhZTA3ZmYwYzFiZGYzYzk4IiwidXNlcl9pZCI6IjEifQ.M-btrv55I-QjaHGQdD_BiWrlT12BmVy8lt3SSzjybrA

{
    "name": "Kundal Protein Bonding Treatment",
    "description": "Violet Muguet",
    "price": "1620.00",
    "stock": 100,
    "category": 1
}

### Get categories list
GET http://127.0.0.1:8000/products/categories/

### Create a Category
POST http://127.0.0.1:8000/products/categories/
Content-Type: application/json

{
    "name": "Fashion",
    "slug": "fashion",
    "description": "Clothing, footwear, and fashion accessories for all ages.",
    "is_active": true
}

### Get detail of a product
GET http://127.0.0.1:8000/products/6/

### Update a product
PUT http://127.0.0.1:8000/products/6/
Content-Type: application/json

{
    "name": "Kundal Protein Bonding Treatment",
    "description": "Violet Muguet",
    "price": "1615.00",
    "stock": 100,
    "category": 1
}

### Partial Update a product
PATCH  http://127.0.0.1:8000/products/6/
Content-Type: application/json

{
    "price": "1630.00"
}

### Delete a product
DELETE  http://127.0.0.1:8000/products/5/